-- Seed Year 1 of The Trivora Global Quiz Rankings (admin can update via dashboard later)
INSERT INTO public.tournaments (
  id,
  type,
  name,
  title,
  description,
  entry_fee_pence,
  prize_pence,
  location_city,
  location_country,
  finals_venue_name,
  registration_opens_at,
  games_begin_at,
  starts_at,
  ends_at,
  finals_at,
  finals_time_window,
  awards_at,
  finals_top_n,
  status
) VALUES (
  'a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d'::uuid,
  'global',
  'The Trivora Global Quiz Rankings',
  'The Trivora Global Quiz Rankings',
  'The flagship annual championship. Qualify through elimination rounds; the Top 16 compete in the Live In-Person Finals. One Global Champion takes home £1,000 and the trophy.',
  500,
  100000,
  'London',
  'GB',
  NULL,
  '2025-03-28 00:00:00+00',
  '2025-04-28 00:00:00+00',
  '2025-04-28 00:00:00+00',
  '2025-06-27 00:00:00+00',
  '2025-06-26 09:00:00+00',
  '9:00am – 3:00pm',
  '2025-06-26 20:00:00+00',
  16,
  'upcoming'
) ON CONFLICT (id) DO UPDATE SET
  type = EXCLUDED.type,
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  entry_fee_pence = EXCLUDED.entry_fee_pence,
  prize_pence = EXCLUDED.prize_pence,
  location_city = EXCLUDED.location_city,
  location_country = EXCLUDED.location_country,
  registration_opens_at = EXCLUDED.registration_opens_at,
  games_begin_at = EXCLUDED.games_begin_at,
  starts_at = EXCLUDED.starts_at,
  ends_at = EXCLUDED.ends_at,
  finals_at = EXCLUDED.finals_at,
  finals_time_window = EXCLUDED.finals_time_window,
  awards_at = EXCLUDED.awards_at,
  finals_top_n = EXCLUDED.finals_top_n,
  status = EXCLUDED.status,
  updated_at = NOW();
